### ISSUE TITLE
`pipsi` depends on an external `virtualenv` even after bootstrapping

### ISSUE THREAD

**Issue by nnutter** [mitsuhiko/pipsi#89]
#### Problem

`pipsi` depends on an external `virtualenv` even after bootstrapping which means it's not fully encapsulated in its `virtualenv`.

#### Possible Solution

Have `pipsi` symlink its `virtualenv` into the `bin_dir`.

#### Context

I tried to install `pipsi` but the system `python` didn't have `virtualenv`,

```
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2805  100  2805    0     0   5000      0 --:--:-- --:--:-- --:--:-- 20326
Installing pipsi
You need to have virtualenv installed to bootstrap pipsi.
```

I use [pyenv](https://github.com/yyuu/pyenv) so I don't "pollute" the system interpreter so I switch to my Python 2.7,

```
$ pyenv shell 2.7.12
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
...
pipsi is now installed.
```

It seems like the goal of `pipsi` is it make self-contained installations so at this point I would expect `pipsi` to no longer depend on an external `virtualenv`; however, it does,

```
$ pyenv shell system
$ ls ~/.local/venvs/pipsi/bin/virtualenv
/home/nnutter/.local/venvs/pipsi/bin/virtualenv
$ pipsi install X
pyenv: virtualenv: command not found

The `virtualenv' command exists in these Python versions:
  2.7.12
  3.5.1

Failed to create virtualenv.  Aborting.
```

A really simple solution would be to have `pipsi` symlink its `virtualenv` into the `bin_dir`.

**Comment by ericfrederich** [comment]
I tried on Linux Mint 18.2 as well as directly on Ubuntu 16.04 (of which Mint 18.2 is based) and ran into this as well.

The issue is especially bad because to even get pipsi to use Python3 I cannot have `virtualenv` installed.  If I have `virtualenv` installed then doing `curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3.5` even though I specified `python3.5` will still create pipsi using a `python2` interpreter.

So I'm in a catch22 situation.  I can't have virtualenv installed to use python3 but I need it installed afterwards in order to use it.

**Comment by gagoman** [comment]
Actually an issue is resolved a year ago by https://github.com/mitsuhiko/pipsi/pull/76

The actual problem is that, by default, `pipsi` is installed from PYPI and version is outdated there.

@mitsuhiko any chance to update it?

**Comment by mmerickel** [comment]
Yes, you can also use the `--src` argument to `get-pipsi`.

curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3 - --src 'git+https://github.com/mitsuhiko/pipsi.git#egg=pipsi'

At this point the chances of pipsi getting a release are so slim that this should probably just be made the default instead of installing from pypi.

**Comment by mitsuhiko** [comment]
I forgot there even is a pypi release. I need to find out why it installs from pypi.

**Comment by yunstanford** [comment]
Any update on this ?

**Comment by dgrant** [comment]
Any update? This is still an issue, the original poster has provided 3 solutions and also 2 PRs.

**Comment by funkyfuture** [comment]
> I forgot there even is a pypi release. I need to find out why it installs from pypi.

yet, intuition comes up with `pip install --user pipsi` when there's an impusle to install pipsi. i therefore recommend it from the pypi if it isn't supposed to be retrieved from there.

> Yes, you can also use the --src argument to get-pipsi.

as this seems to be the only working method to install pipsi (on an Arch Linux system), the README should be updated accordingly.
